# Python quiz game
# Most questions are generated by ChatGPT

questions = (
	"How many elements are in the periodic table?",
	"Which animal lays the largest eggs?",
	"What is the most abundant gas in Earth's atmosphere?",
	"How many bones are in the human body?",
	"Which planet in the solar system is the hottest?",
	"Which country is the largest by land area?",
	"Who painted the Mona Lisa?",
	"What is the capital city of Australia?",
	"Which is the tallest mountain in the world?",
	"Who is the author of the Harry Potter book series?",
	"What is the chemical symbol for gold?",
	"Which is the largest ocean on Earth?",
	"In which year did World War II end?",
	"What is the national animal of India?",
	"Which is the largest desert in the world?",
	"Who invented the telephone?",
	"Which is the largest species of shark?",
	"What is the currency of Japan?",
	"Which is the longest river in Africa?",
	"What is the main component of the Earth's core?"
)

options = (
	("A. 116", "B. 117", "C. 118", "D. 119"),
	("A. Whale", "B. Crocodile", "C. Elephant", "D. Ostrich"),
	("A. Nitrogen", "B. Oxygen", "C. Carbon Dioxide", "D. Hydrogen"),
	("A. 206", "B. 207", "C. 208", "D. 209"),
	("A. Mercury", "B. Venus", "C. Earth", "D. Mars"),
	("A. China", "B. Canada", "C. Russia", "D. United States"),
	("A. Michelangelo", "B. Leonardo da Vinci", "C. Pablo Picasso", "D. Vincent van Gogh"),
	("A. Sydney", "B. Melbourne", "C. Canberra", "D. Perth"),
	("A. Himalayas", "B. K2", "C. Kanchenjunga", "D. Mount Everest"),
	("A. Dan Brown", "B. Stephen King", "C. George R.R. Martin", "D. J.K Rowling"),
	("A. Cu", "B. Ag", "C. Au", "D. Fe"),
	("A. Arctic Ocean", "B. Atlantic Ocean", "C. Indian Ocean", "D. Pacific Ocean"),
	("A. 1945", "B. 1939", "C. 1941", "D. 1943"),
	("A. Lion", "B. Tiger", "C. Elephant", "D. Peacock"),
	("A. Gobi", "B. Arabian", "C. Sahara", "D. Kalahari"),
	("A. Alexander Graham Bell", "B. Thomas Edison", "C. Isaac Newton", "D. Albert Einstein"),
	("A. Tiger Shark", "B. Great White Shark", "C. Hammerhead Shark", "D. Whale Shark"),
	("A. Pound", "B. Rial", "C. Euro", "D. Yen"),
	("A. Congo", "B. Nile", "C. Niger", "D. Zambezi"),
	("A. Iron", "B. Nickel", "C. Both A & B", "D. None of them")
)

# answer key
answers = ("C", "D", "A", "A", "B", "C", "B", "C", "D", "D", "C", "D", "A", "B", "C", "A", "D", "D", "B", "C")
int_ans = ("3", "4", "1", "1", "2", "3", "2", "3", "4", "4", "3", "4", "1", "2", "3", "1", "4", "4", "2", "3")

guesses = []
score = 0

# colors
light_blue = "\033[94m"
light_green = "\033[92m"
light_yellow = "\033[93m"
green = "\033[32m"
blue = "\033[96m"
bold = "\033[1m"
reset_color = "\033[0m"

# quiz game starts
print(light_blue + "Welcome to the Quiz Game!" + reset_color)
print(light_green + "--------------------------" + reset_color)

for question_num in range(len(questions)):
	print(f"{question_num + 1}. {questions[question_num]}")
	for option in options[question_num]:
		print(option)
	guess = input("Option: ").capitalize()  # .upper() should be used, but I like .capitalize()
	guesses.append(guess)
	print(light_yellow + "---------------------------------------------" + reset_color)

	if guess == answers[question_num] or guess == int_ans[question_num]:
		score += 1

# prints the results with an answer key
print(light_blue + bold + "                  RESULTS                    " + reset_color)
print(light_yellow + "---------------------------------------------" + reset_color)

print(bold + "Questions, Answers, and Guesses:" + reset_color)
print()

for i in range(len(questions)):
	print(f"{i + 1}. {questions[i]}")
	for option in options[i]:
		print(option)
	print(f"Correct Answer: {answers[i]}")
	if guesses[i] == "1"  or guesses[i] == "A":
		guesses[i] = "A"
	elif guesses[i] == "2"  or guesses[i] == "B":
		guesses[i] = "B"
	elif guesses[i] == "3"  or guesses[i] == "C":
		guesses[i] = "C"
	elif guesses[i] == "4"  or guesses[i] == "D":
		guesses[i] = "D"
	else:
		guesses[i] = "⁇"
	print(f"Your Guess: {guesses[i]}")
	print()

# prints the final score
score = int(score / len(questions) * 100)
print(f"{bold}{blue}Score: {score}%{reset_color}")
